### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by Jztsbo** [ICTMCG/News-Environment-Perception#3]
Hello!I meet this error:
$ /bin/sh E:/code/nlp/News-Environment-Perception/preprocess/SimCSE/train_SimCSE/train.sh
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
The error is at News-Environment-Perception/preprocess/SimCSE/train_SimCSE/train.py  line 16.
I also can't find the module named 'datasets' in the project.Can you submit it or tell me how to download it? :）

**Comment by sheng-qiang** [comment]
Hi, this is an external package and you may install it via *pip install*.
