### ISSUE TITLE
Application Datasets 

### ISSUE THREAD

**Issue by 153zml** [ICTMCG/News-Environment-Perception#4]
I am very interested in your work and want to do further research. I wonder if you can send me the data set you used. The email address is zml1538576428@163.com. I will be very grateful for any reply

**Comment by sheng-qiang** [comment]
Please fill in the application form, the relevant resource will be sent to you by email.

https://forms.office.com/r/Tr6FMGQJt0

P.S.: We can only send the resource link to email addresses of academic institutions to ensure that this is only for academic purposes. Please do not use your 163 email address in the application form.
